# Docker Compose for Production Environment
version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: personal-resume-web-prod
    ports:
      - "8080:8080"
    environment:
      - PYTHONPATH=/app
      - ENV=production
      - WORKERS=4
    volumes:
      - logs:/app/logs
    restart: always
    networks:
      - resume-network
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  nginx:
    image: nginx:alpine
    container_name: personal-resume-nginx-prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      web:
        condition: service_healthy
    restart: always
    networks:
      - resume-network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 128M

networks:
  resume-network:
    driver: bridge
    name: personal-resume-network-prod

volumes:
  logs:
    name: personal-resume-logs-prod
