# Docker Compose for Personal Resume Website
version: '3.8'

services:
  # Main web application
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: personal-resume-web
    ports:
      - "8080:8080"
    environment:
      - PYTHONPATH=/app
      - ENV=development
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - resume-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Nginx reverse proxy (optional, for production-like setup)
  nginx:
    image: nginx:alpine
    container_name: personal-resume-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - web
    restart: unless-stopped
    networks:
      - resume-network
    profiles:
      - production

# Networks
networks:
  resume-network:
    driver: bridge
    name: personal-resume-network

# Volumes
volumes:
  logs:
    name: personal-resume-logs
